
import { supabaseCustom } from '@/integrations/supabase/client-custom';
import { PurchaseOrderStatusCode } from '@/types/purchaseOrder';

interface CreatePurchaseOrderInput {
  organizationId: string;
  printRunId: string;
  supplierId?: string;
  supplierQuoteId?: string;
  currency: string;
  issueDate?: Date;
  deliveryDate?: Date;
  shippingMethod?: string;
  shippingAddress?: string;
  notes?: string;
  createdBy: string;
  status?: 'draft' | 'pending_approval';
  statusCode?: PurchaseOrderStatusCode;
}

export async function createPurchaseOrder({
  organizationId,
  printRunId,
  supplierId,
  supplierQuoteId,
  currency,
  issueDate,
  deliveryDate,
  shippingMethod,
  shippingAddress,
  notes,
  createdBy,
  status = 'draft',
  statusCode = '00',
}: CreatePurchaseOrderInput): Promise<string> {
  // Create the purchase order
  // Note: po_number is generated by a database trigger so we don't need to include it
  const { data, error } = await supabaseCustom
    .from('purchase_orders')
    .insert({
      organization_id: organizationId,
      print_run_id: printRunId,
      supplier_id: supplierId,
      supplier_quote_id: supplierQuoteId,
      currency,
      issue_date: issueDate,
      delivery_date: deliveryDate,
      shipping_method: shippingMethod,
      shipping_address: shippingAddress,
      notes,
      status,
      status_code: statusCode,
      created_by: createdBy,
    } as any) // Using type assertion to bypass the TypeScript error
    .select('id, po_number')
    .single();

  if (error) {
    console.error('Error creating purchase order:', error);
    throw error;
  }

  const purchaseOrderId = data.id;

  // Create audit entry
  await supabaseCustom.rpc('record_purchase_order_audit', {
    p_purchase_order_id: purchaseOrderId,
    p_changed_by: createdBy,
    p_action: 'create',
    p_changes: { status, status_code: statusCode },
  });

  return purchaseOrderId;
}
