
import { z } from "zod";

export const productSchema = z.object({
  title: z.string().min(1, "Title is required"),
  subtitle: z.string().optional(),
  isbn13: z.string().optional(),
  isbn10: z.string().optional(),
  publication_date: z.date().nullable().optional(),
  publisher_name: z.string().optional(),
  product_form: z.string().optional(),
  product_form_detail: z.string().optional(),
  list_price: z.number().nullable().optional(),
  currency_code: z.string().optional(),
  series_name: z.string().optional(),
  language_code: z.string().optional(),
  product_availability_code: z.string().optional(),
  subject_code: z.string().optional(),
  synopsis: z.string().optional(),
  selling_points: z.string().optional(),
  age_range: z.string().optional(),
  page_count: z.number().nullable().optional(),
  edition_number: z.number().nullable().optional(),
  cover_image_url: z.string().optional(),
  internal_images: z.array(z.string()).optional(),
  height_measurement: z.number().nullable().optional(),
  width_measurement: z.number().nullable().optional(),
  thickness_measurement: z.number().nullable().optional(),
  weight_measurement: z.number().nullable().optional(),
  format_id: z.string().nullable().optional(),
  carton_quantity: z.number().nullable().optional(),
  carton_length_mm: z.number().nullable().optional(),
  carton_width_mm: z.number().nullable().optional(),
  carton_height_mm: z.number().nullable().optional(),
  carton_weight_kg: z.number().nullable().optional(),
  license: z.string().optional(),
  format_extras: z.array(z.object({
    name: z.string(),
    description: z.string().optional(),
    unit_of_measure_id: z.string().optional(),
  })).optional(),
  format_extra_comments: z.string().nullable().optional(),
  status: z.string().optional(),
});

export type ProductFormValues = z.infer<typeof productSchema>;

export const defaultProductValues: ProductFormValues = {
  title: "",
  subtitle: "",
  isbn13: "",
  isbn10: "",
  publication_date: null,
  publisher_name: "",
  product_form: "",
  product_form_detail: "",
  list_price: null,
  currency_code: "USD",
  series_name: "",
  language_code: "",
  product_availability_code: "",
  subject_code: "",
  synopsis: "",
  selling_points: "",
  age_range: "",
  page_count: null,
  edition_number: null,
  cover_image_url: "",
  internal_images: [],
  height_measurement: null,
  width_measurement: null,
  thickness_measurement: null,
  weight_measurement: null,
  format_id: null,
  carton_quantity: null,
  carton_length_mm: null,
  carton_width_mm: null,
  carton_height_mm: null,
  carton_weight_kg: null,
  license: "",
  format_extras: [],
  format_extra_comments: null,
  status: "active",
};
