
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzguoukmiwxvqdnabfma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6Z3VvdWttaXd4dnFkbmFiZm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwODIxMDcsImV4cCI6MjA1NjY1ODEwN30.3-y83UCuzWeYtjBpFRiM73NpVg0GTbI_VoJj_evFDFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
